### ISSUE TITLE
Subscribe page

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#132]
New page `/subscribe` that when opened pops a modal with the following script:

```
<script src="https://js.chargebee.com/v2/chargebee.js" data-cb-site="mainstay-test" ></script>
<a href="javascript:void(0)" data-cb-type="checkout" data-cb-plan-id="mainstay-standard" >subscribe</a>
```

The background should show the mainstay website template. When the modal is closed, it should redirect to `/home`.

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas is it correct to have data-cb-site="mainstay-test" and data-cb-plan-id="mainstay-standard" in the above script?
