### ISSUE TITLE
Automate latest txid sent to clients

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mainstay-mvc#146]
To do a 'full' verification of a list of commitments against a staychain, it must be verified that each transaction in the staychain (from the initiation txid) contains a commitment from the sidechain headers in sequence OR a null commitment (i.e. zero). 

So when a user signs up, they should be provided the current (latest) TxID of the staychain (to commit to their genesis) and then a zero (0x0000...) commitment added to the next staychain transaction, and every subsequent transaction, until they make their first commitment.

**Comment by nkostoulas** [comment]
Currently committing zeros after sign up. Need to do anything else for this? I guess we can add the latest txid in the email we send to users.

**Comment by nkostoulas** [comment]
added to #171
