### ISSUE TITLE
API: AttestationProof

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mainstay-mvc#147]
To fully verify the sequence of commitments from the latest proof down to the base transaction, requires the following sequence with the current API when we don't know the commitment yet (because we don't know which sidechain block was committed):

1. Get the prevout txid from Bitcoin/Electrum RPC
2. Get the attestation info using the attestation?txid call. 
3. Use the merkle_root and position (slot) to get the proof with commitment/proof?position=pos&merkle_root=root - this returns both the proof and the commitment. 
4. Verify proofs and match commitment with sidechain block. 

It would be more efficient to be able to get: merkle-root, proof path and commitment in a single call, given just the attestation txid and the position. 

For faster initial syncing, being able to batch the requests would also be faster: i.e. given a staychain txid, position and integer n, return the previous n attestations (including merkle_root, proof and commitment).

**Comment by nkostoulas** [comment]
We have the position call, latest commitment/proof/attestation calls and proof calls by commitment/position/root. Should we add something else? Maybe an AttestationProof or do the other suffice?

**Comment by nkostoulas** [comment]
@Vardan-Alaverdyan we need a new API call `attestation/proof` that takes an attestation "txid" and the client position as inputs. It returns the same data as the `commitment/proof` call. To get this data, you first need to query the Attestation collection with the attestation "txid" to get the "merkle_root" and then use that to query the MerkleProof collection. 

Please also add an example in the api docs.
