### ISSUE TITLE
Front: flickering when clicking Mainstay (home) button from other views

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#153]

**Comment by nkostoulas** [comment]
Also when refreshing

**Comment by nkostoulas** [comment]
@Vardan-Alaverdyan refreshing and clicking on mainstay logo still a problem

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas 
It is flickering because the browser sends one or more requests for each page.
It sends a request even when I enter the same page the second time. I can fix this by showing cached data and update the view after receiving the response. I need to implement redux-store for this.
Please share your suggestions too.

**Comment by nkostoulas** [comment]
Why does it happen when you click the icon though and it doesn’t happen when you click “MainStay”?

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas please share a video
BTW, I am testing this on user_auth_backend_149 branch and I don't see any difference between.

**Comment by nkostoulas** [comment]
You are right I get the same flickering on both.

**Comment by nkostoulas** [comment]
Let's park this a bit.

**Comment by nkostoulas** [comment]
> Implement Redus Store for each view, and cache every response .
> Implement actions, reducers for all request/responses - ~6 hours
> We have the following views:
> 1. Overview
> 2. Last Attestation
> 3. Last Commitment
> 4. Attestations list
> 5. Clients List
> make appropriate changes and do the alpha test for each view - ~2.
> Unlikely, but these changes can lead to some unexpected changes too, as the app is not built redux-store in mind.
> So to avoid previews experience that we had (regarding timeline issues) approximately estimation is ~20 hours.
