### ISSUE TITLE
Front: "Send Commitment" modal placeholders

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#154]
Placeholder values are slightly confusing. Especially on "Commitment" and "Signature" where they don't even fit in the whole line. Might be good to increase the textbox on those two. Also I think we should either remove the placeholders or clear the textbox when selected.

**Comment by nkostoulas** [comment]
Also if you close the modal and then re open, the modal remembers the previous values even though the displayed text is blank. It should either show the previous values or clear the history.

**Comment by nkostoulas** [comment]
Also "CommitmentModal.jsx" doesn't seem to be used.

**Comment by Vardan-Alaverdyan** [comment]
> Also "CommitmentModal.jsx" doesn't seem to be used.

if you mean the "SendCommitmentModal.jsx": it is used.

**Comment by Vardan-Alaverdyan** [comment]
> Also if you close the modal and then re open, the modal remembers the previous values even though the displayed text is blank. It should either show the previous values or clear the history.

@nkostoulas please check this, should be fixed

**Comment by nkostoulas** [comment]
> Placeholder values are slightly confusing. Especially on "Commitment" and "Signature" where they don't even fit in the whole line. Might be good to increase the textbox on those two. Also I think we should either remove the placeholders or clear the textbox when selected.

@Vardan-Alaverdyan this still

**Comment by nkostoulas** [comment]
reverted with merge
