### ISSUE TITLE
Automate: pricing information and subscription

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#171]
Following successful KYC send email with pricing information to the user.

**Comment by nkostoulas** [comment]
The link to be sent. https://mainstay.xyz/subscribe

**Comment by nkostoulas** [comment]
@Vardan-Alaverdyan with improving the modal. Then create the process for sending a new email when KYC has been approved (i.e. kyc_ok). The email should include the subscribe link.

Still waiting from @Dirk-Bernhardt if we want to include any other information in this email.

**Comment by Dirk-Bernhardt** [comment]
I sent the two email templates to Nikos. 1) the initial signup confirmation
and 2) the KYC confirmation upon successful KYC

As a last step, we should then have a template email for confirmation of
successful subscription that also contains the slot info. Or is there
another way to convey the slot info other than email?

D

*   Dirk Bernhardt *| *COO*
<https://www.commerceblock.com/>
*    M:* +44 (0)7496 044593   *P**:* +44 (0)20 38232200  *E:*
dirk@commerceblock.com

ᐧ

**Comment by nkostoulas** [comment]
[mainstay-subscribe-email.rtfd.zip](https://github.com/commerceblock/mainstay-mvc/files/4387897/mainstay-subscribe-email.rtfd.zip)

email template

**Comment by nkostoulas** [comment]
> Or is there another way to convey the slot info other than email?

Best way would be via email yes. First we need to figure out the API of the payment provider as we would require to query them for whether a specific email/user has subscribed. After that the new slot can be generated and sent to the user.

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas 
What should we show on:
1. chargebee checkout error
2. chargebee checkout success
3. chargebee checkout close 

Should we should we show some congrats dialog on success?...

**Comment by nkostoulas** [comment]
Just show the chargebee dialog with mainstay home as background. When the dialog closes just continue showing the home page.
