### ISSUE TITLE
Front: new t&c

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#172]

**Comment by Vardan-Alaverdyan** [comment]
1. please check this word:  _**supercede**_ (2.Changes to These Terms.)
2. The list items in:
- 15.3 and 7.2:  a), b) (closing bracket only)
- 12.1: (a), (b)  (opening and closing brackets)
which one is correct?

**Comment by nkostoulas** [comment]
ping Dirk
