### ISSUE TITLE
Front: The pricing link in the footer leads to the Home page

### ISSUE THREAD

**Issue by Vardan-Alaverdyan** [commerceblock/mainstay-mvc#175]
Is it ok or we need to remove the link?

**Comment by nkostoulas** [comment]
When we add the new pricing page we should remove the link.

**Comment by nkostoulas** [comment]
"""
Regarding flickering issue, here you can find detailed description and estimation
Implement Redus Store for each view, and cache every response .
Implemet actions, reducers for all request/responses - ~6 hours
We have the following views:
1. Overview
2. Last Attestation
3. Last Commitment
4. Attestations list
5. Clients List
make appropriate changes and do the alpha test for each view - ~2.
Unlikely, but these changes can lead to some unexpected changes too, as the app is not built redux-store in mind.
So to avoid previews experience that we had (regarding timeline issues) approximately estimation is ~20 hours.
"""

**Comment by Vardan-Alaverdyan** [comment]
we agreed to remove the link for now
