### ISSUE TITLE
Backend: check duplicate emails on signup

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#179]
Re-enable ClientSignup table, with fields "email", "first name", "last name".

Each time a new user signs up, insert a new entry in that table. If the email already exists then display an appropriate error message and reject the sign up.

We need a new tab in the admin page that displays the ClientSignup table.

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas 
previously we also had company, public_key fields and client_name instead of "first name", "last name".
Should I changed the sign-up popup? 
What to do with public_key and company?

**Comment by nkostoulas** [comment]
OK I guess store all of them. And split name into two fields.

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas Are both First Name and Last Name required in SignUp dialog?

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas 
"A user with same email already exists."
Is this error message OK?

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas 
do we need  to have a "Add Client" and "Edit" client functionality?

**Comment by nkostoulas** [comment]
Yes
Ok
No

**Comment by nkostoulas** [comment]
Users are added to the table when they signup and only if sign up succeeds. An email notification is sent to us. Through the /admin form we can see who signed up. With this information we initiate KYC. We will later automate this.
