### ISSUE TITLE
Front: error should not show on signup

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#238]
![photo_2020-02-03 12 56 20](https://user-images.githubusercontent.com/14759579/74149807-85663380-4c00-11ea-9fd6-086e12fe8906.jpeg)

**Comment by stakauskas** [comment]
Better would be to not provide debug information on any occasion.

**Comment by nkostoulas** [comment]
Db or any other internal errors should be logged but a default error message should be displayed to the user.

**Comment by Vardan-Alaverdyan** [comment]
Can we show a message something like "Something went wrong. Please contact Mainstay support." in case of internal server error (with status code 500)?
