### ISSUE TITLE
Automate: signup email sending

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#239]
This should also be done by the signups service and not the mainstay backend.

**Comment by nkostoulas** [comment]
Also send an email to the user.
[mainstay.signup.email.rtfd.zip](https://github.com/commerceblock/mainstay-mvc/files/4231460/mainstay.signup.email.rtfd.zip)

**Comment by nkostoulas** [comment]
Move the signup email and the user email to the signup service (`src/signup.js`). Feel free to add new states if you think is required but don't change the current logic.

**Comment by Vardan-Alaverdyan** [comment]
We send an email to the admin on user signup (EmailToAdmin). 
Now we need to send an email to the user after KYC sent and move the EmailToAdmin from the controller to the signups.js. Am I right?
I case I am right, when should I send EmailToAdmin email: after KYC sent or before?

**Comment by nkostoulas** [comment]
Correct. Whenever a new user signs up this gets to ClientSignup with status "new". After this happens, send an email to admin, send an email to the user and then send the KYC.
