### ISSUE TITLE
Front: Add FeedBack for Modal - Send Commitment

### ISSUE THREAD

**Issue by lodenos** [commerceblock/mainstay-mvc#24]
Add Alert with style Bootstrap ( Color Success ) in Top page and show just 5 seconds

**Comment by nkostoulas** [comment]
<img width="881" alt="49739449-d3dd1280-fc89-11e8-8b1d-6646a46878bc" src="https://user-images.githubusercontent.com/14759579/49740146-82ce1e00-fc8b-11e8-9cc4-83da7366910a.png">

**Comment by nkostoulas** [comment]
Success/failure alert.

To test success, get latest dbTest data from "develop" and do:

Position: 16
Token: a7903cf3-c224-467c-b3e3-10f16e3eb896
Commitment: 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943
Signature: IE3TJLTyCePjTHXpwhhWuPf9qSTXELMS5sdVsfR0ESJrKvCT/t/CQmpiG0OBYzbbj+bdUak2z814M1/XnQuAhRU=
