### ISSUE TITLE
Automate: new user attestation slot

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#246]
Is there a way to check if users have subscribed?

Create a slot and email users along with the latest txid once user has subscribed.

**Comment by nkostoulas** [comment]
We need to check that a user has subscribed (i.e. agreed to monthly payments). To do this we need to examine if there is any API via chargebee. @Dirk-Bernhardt do you have any info for this that you can point @Vardan-Alaverdyan to?

We'll need a interval that checks all entries with "kyc_ok" so see if they are verified, mark the user as "payment_ok" and create a new entry in ClientDetails and ClientCommitment (the exact same way it's done in client details admin page). Once the new slot has been allocated, mark the user as "slot_ok".

We will also need to send an email to the user including the information required for sending commitments to mainstay, along with any other information we want to share. These are:
- Position number
- Auth token
@Dirk-Bernhardt we'll need another email template for this.

**Comment by Dirk-Bernhardt** [comment]
Below is the Chargebee API info:

https://apidocs.chargebee.com/docs/api

I'll make a simple email template to share the info with a new client. With
regards to making commitments, i would maybe do a very simple step
description and then refer to the tech documentation on readthedocs to keep
the email short and distinct.

D

*   Dirk Bernhardt *| *COO*
<https://www.commerceblock.com/>
*    M:* +44 (0)7496 044593   *P**:* +44 (0)20 38232200  *E:*
dirk@commerceblock.com

ᐧ

**Comment by Vardan-Alaverdyan** [comment]
After redirecting to the subscribe page from email, user can fill other email address in the chargebee-checkout form. We can pre-fill email, first name, last name in  but the user can change the pre-filled email.
Does this mean that we will lose connection between signup-user and chargebee customer.
if yes, I suggest to generate a key, link the user and the chargebee-subscription to that key.

**Comment by nkostoulas** [comment]
I guess we were assuming they would use the same email.

Even with the key you suggest, how do we know the user actually subscribed?

**Comment by Vardan-Alaverdyan** [comment]
After chargebee subscription new entry is added in the clientDetails collection with `pubkey: '', auth_token: uuidv4()` new entry is added in the clientCommitment with `commitment: '0000000000000000000000000000000000000000000000000000000000000000'`

I need email template for payment_ok/slot_ok

**Comment by nkostoulas** [comment]
@Vardan-Alaverdyan I assume you've incremented position similar to how we do it in admin page. Pubkey is optional but might be included by some users.

@Dirk-Bernhardt we'll need an email template that informs users their subscription were successful and where we share the following:
- auth token
- position

**Comment by Dirk-Bernhardt** [comment]
Nikos, sent you a template draft. Let me know if that makes sense.

D
ᐧ

**Comment by nkostoulas** [comment]
> Nikos, sent you a template draft. Let me know if that makes sense. D ᐧ
> […](#)

Sure looks great!

@Vardan-Alaverdyan 
[mainstay.email.confirmed.rtfd.zip](https://github.com/commerceblock/mainstay-mvc/files/4450688/mainstay.email.confirmed.rtfd.zip)
