### ISSUE TITLE
Front - Fix Home page

### ISSUE THREAD

**Issue by lodenos** [commerceblock/mainstay-mvc#28]
Add Content for show Slots in front

**Comment by nkostoulas** [comment]
@lodenos 
In LatestCommitment

remove merkle_root (since you can see in Latest Attestation)
rename confirmed - > commitment
add Client Name columnt (taken from ClientDetails collection)

**Comment by nkostoulas** [comment]
In both LatestAttestation / LatestCommitment in Home page, fix column margins

**Comment by lodenos** [comment]
<img width="881" alt="screenshot 2018-12-10 at 14 41 28" src="https://user-images.githubusercontent.com/16132777/49739448-d3dd1280-fc89-11e8-85c2-2676e0a36451.png">
<img width="881" alt="screenshot 2018-12-10 at 14 38 00" src="https://user-images.githubusercontent.com/16132777/49739449-d3dd1280-fc89-11e8-8b1d-6646a46878bc.png">

**Comment by nkostoulas** [comment]
- [ ] Add CBT icon (https://github.com/commerceblock/ocean-explorer) in website, favicon,... Change displayed page name to "Mainstay Explorer"

- [ ] Fix column margins

- [ ] Concatenate data to fit, move "..." to line below

- [ ] Centre alignment for columns and data in Latest Attestation and Latest Commitment

- [ ] Date in single line

- [ ] Fixed size height; 50% for Latest Attestation, 50% for LatestCommitment

- [ ] Remove MerkleRoot column and data from LatestCommitment. Rename Confirmed -> Commitment in LatestCommitment

If you could start with these @Vardan-Alaverdyan and we can discuss further changes.

**Comment by nkostoulas** [comment]
also rename "Age" to "Date" or something
