### ISSUE TITLE
Removing the requirement for a KYC/ID 

### ISSUE THREAD

**Issue by Vardan-Alaverdyan** [commerceblock/mainstay-mvc#283]
After the sign-up has been submitted, instead of the next step being forwarded to Onfido, we want the user to have to simply confirm their email address. If they selected the 'free' level, then the slot would be activated (create_slot) straigt away. If a paid level, then they would be sent to make the payment, and the status updated when successful.

**Comment by Vardan-Alaverdyan** [comment]
@tomt1664 I need email-template for email-address  confirmation.
Also can you please explain in more detail what should I show after email confirmation, what should be added in the database

**Comment by tomt1664** [comment]
Email template for email address confirmation:

`<!DOCTYPE html>
<html lang="en">
<body>
<div style="max-width:800px; margin:0 auto; font-family: Helvetica,serif">
    <div style="text-align: center">
        <img alt="MainStay" src="$$MAIN-STAY-LOGO-URL$$" />
    </div>

    <p style="text-align: center">Dear $$NAME$$, thank you for signing up to our MainStay service!</p>
    <div style="text-align: center">Please click here to confirm your email address.</div>
    <ol style="margin-top: 0">
        <li>If you have selected a paid service level, you will shortly receive instructions on how to set-up monthly payment via our payments processor.</li>
        <li>If you have selected the free service, your slot will be allocated and activated. </li>
        <li>You will then receive an email containing your slot ID and API credentials.</li>
    </ol>

    <br />
    <div style="text-align: center">
        <div>Then you can start securing and verifying your documents and data!</div>
        <p>
            For any technical assistance, please refer to our guidance documents under:
            <br>
            <a href="https://commerceblock.readthedocs.io/en/latest/mainstay/index.html">MainStay - Technical
                documentation</a>
            <br />
        </p>

        <p>
            If you have any questions or issues, please contact us under <a href="mailto:support@mainstay.xyz">support@mainstay.xyz</a>.
        </p>
        <br />
        <p>Your CommerceBlock Team</p>
        <div style="text-align: center">
            <img alt="CommerceBlock" src="$$COMMERCE-BLOCK-LOGO-URL$$" />
        </div>
    </div>
</div>
</body>
</html>`

**Comment by tomt1664** [comment]
@Vardan-Alaverdyan  service_level can be one of: 'free', 'basic', 'intermediate' and 'enterprise'. 
`signup` 
If 'free' then after email confirmation, we go straight to `create_slot()`. The `clientDetails` has a new client added (with the service level included - i.e. `const level = signup.service_level`). `sendPaymentOkEmail` and the template can remain as it is. 
If service_level is 'basic', 'intermediate' or 'enterprise', then after email confirmation, we send the 'subscribe.html' email for payment. I'm not sure where we specify the amount - I guess this is passed to the payment processor? Each of the 3 different service_levels have a different monthly fee.

**Comment by Vardan-Alaverdyan** [comment]
@tomt1664 now we use Chargebee product called `mainstay-standard`. 
I think we need to create a new products for each `service_levels `.

**Comment by tomt1664** [comment]
@Vardan-Alaverdyan `mainstay-standard`, `mainstay-intermediate` and `mainstay-enterprise` are now supported in Chargebee.

**Comment by Vardan-Alaverdyan** [comment]
@tomt1664 `mainstay-standard` plan work like expected, but I receive error for `mainstay-intermediate` and `mainstay-enterprise`
[video](https://www.dropbox.com/s/ah8hegnogndz2wo/Screen%20Recording%202020-09-03%20at%2013.01.50.mov?dl=0)

**Comment by tomt1664** [comment]
@Vardan-Alaverdyan Were you using the `mainstay` or `mainstay-test` site? I have set up all three plans on both now (only on the live site before)?

**Comment by Vardan-Alaverdyan** [comment]
I am using `mainstay-test`

**Comment by harutlc** [comment]
works
@tomt1664 After success/failed email verification we need to show some message(modal). like: "verified successfully.... check your email..."
can you please provide the message?

**Comment by tomt1664** [comment]
OK - it should work now.

**Comment by Vardan-Alaverdyan** [comment]
yes, it works
after success/failed email verification we need to show some message (modal) like: "your email verified successfully, we sent you another email, please check it....."
@tomt1664 can you please provide content for that modal ?

**Comment by tomt1664** [comment]
@Vardan-Alaverdyan 
For the first:
"Email successfully verified. You will shortly receive another email with instructions for setting up monthly payments to activate the service."

For the `free` plan: "Email successfully verified. You will shortly receive another email containing your Mainstay slot ID allocation and API access token."
