### ISSUE TITLE
Front: /api-docs page

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#34]
Page with information on mainstay API

move https://github.com/commerceblock/mainstay-mvc/blob/develop/doc/mainstay_api.md to api information page (on menu).

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas do you need to create a new page which will contain the same information as [mainstay_api.md]( https://github.com/commerceblock/mainstay-mvc/blob/develop/doc/mainstay_api.md) or you just need simple redirection to it on GitHub?

**Comment by nkostoulas** [comment]
I guess a link to that would be good enough.

**Comment by nkostoulas** [comment]
Make it open in a new page better.
