### ISSUE TITLE
Front: add securosys logo

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#66]
`public/securosys.png`

**Comment by nkostoulas** [comment]
https://www.linkedin.com/pulse/assets-securities-cryptocurrency-nicholas-gregory/

**Comment by nkostoulas** [comment]
Add logo next to CB logo before the search bar.

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas how it looks?
<img width="1920" alt="screen shot 2019-01-18 at 11 36 53 pm" src="https://user-images.githubusercontent.com/5110801/51409189-800ff400-1b7a-11e9-87ad-20cb204c17b5.png">

**Comment by nkostoulas** [comment]
Looks good to me.
