### ISSUE TITLE
Front: dates not correct

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#80]
Attestation dates show day/month/year for today but time only for a few days ago.

I think what happens is the date you compare is the date the server was turned on not the current date.

check ctrl_latest_attestation

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas how it looks?
 
<img width="1920" alt="screen shot 2019-01-18 at 11 36 53 pm" src="https://user-images.githubusercontent.com/5110801/51409035-18f23f80-1b7a-11e9-8505-b269bf06b7b0.png">

**Comment by nkostoulas** [comment]
Remember when we said that if a database entry is today we hide dd/mm/yyyy, while if it is older we show it?

That is for today (page 1 https://testnet.mainstay.xyz/attestation)

<img width="1920" alt="51409189-800ff400-1b7a-11e9-87ad-20cb204c17b5" src="https://user-images.githubusercontent.com/14759579/51425952-4a4f2780-1bdb-11e9-9f3e-bd15d12e236b.png">


That is on 15th and 16th (page 4 https://testnet.mainstay.xyz/attestation)

<img width="1920" alt="51409189-800ff400-1b7a-11e9-87ad-20cb204c17b5" src="https://user-images.githubusercontent.com/14759579/51425959-5b983400-1bdb-11e9-85bf-93056b0834c8.png">

**Comment by nkostoulas** [comment]
I think because var now = new Date(); is global and set when website starts and never updated.

It needs to be local and updated on each call to ctrl_latest_attestation().

**Comment by nkostoulas** [comment]
Nevermind I'll fix this.
