### ISSUE TITLE
Front: no error handling on invalid search

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#85]
Searching with invalid input causes web to hang or show a blank page. Fix.

**Comment by Vardan-Alaverdyan** [comment]
@nkostoulas Do you have specific "404, page not found" page or some design for it? Or you want to show in that case just message?

**Comment by nkostoulas** [comment]
Show an error message:
"Search does not match any valid client position, attestation transaction id or commitment hash."

Either in a new page inside an error text box or hover below the search bar (e.g. try an invalid search here https://cbtexplorer.com). Whatever you find easier.
